// Run with metadata generated by app.property_rules.public_rules() on stdin.
// These are pure JavaScript unit checks, not browser/DOM automation.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const wizard = require('../app/static/js/property-form.js');
const metadata = JSON.parse(fs.readFileSync(0, 'utf8'));
let checks = 0;
for (const type of Object.keys(metadata.types)) {
  for (const transaction of metadata.transactions) {
    const rules = metadata.types[type].transactions[transaction];
    const flow = wizard.flow(metadata, type, transaction);
    assert.equal(flow.includes('occupancy'), rules.property_occupancy !== 'inapplicable');
    assert.equal(flow[0], 'purpose');
    assert.equal(flow.at(-1), 'review');
    assert.ok(flow.indexOf('location') < flow.indexOf('details'));
    const entries = Object.keys(metadata.labels).map(name => ({name, value: '0'}));
    assert.deepEqual(wizard.reviewFields(metadata, type, transaction, entries).map(entry => entry.name),
      entries.filter(entry => rules[entry.name] !== 'inapplicable').map(entry => entry.name));
    checks++;
  }
}
assert.equal(wizard.required(metadata, 'floor', 'apartment', 'rent'), true);
assert.equal(wizard.required(metadata, 'floor', 'house', 'rent'), false);
assert.equal(wizard.applicability(metadata, 'land', 'sale').bedrooms, 'inapplicable');
assert.equal(wizard.applicability(metadata, 'warehouse', 'rent').bedrooms, 'inapplicable');
metadata.original = {property_type: 'apartment', transaction_type: 'rent'};
metadata.legacy_missing = ['floor', 'size'];
assert.equal(wizard.required(metadata, 'floor', 'apartment', 'rent'), false);
assert.equal(wizard.required(metadata, 'floor', 'apartment', 'sale'), true);
assert.deepEqual(wizard.reviewFields(metadata, 'land', 'sale', [
  {name: 'bedrooms', value: 3}, {name: 'rent_period', value: 'monthly'},
  {name: 'size', value: 0}, {name: 'floor', value: null}, {name: 'land_use', value: ''}
]), [{name: 'size', value: 0}]);
assert.deepEqual(wizard.reviewFields(metadata, 'land', 'sale', [
  {name: 'description_ar', value: 'Description'}, {name: 'comment', value: 'Separate note'}
]), [{name: 'description_ar', value: 'Description'}, {name: 'comment', value: 'Separate note'}]);
assert.deepEqual(wizard.reviewFields(metadata, 'apartment', 'rent', [
  {name: 'comment', value: '  '}, {name: 'comment', value: null}
]), []);
const emptyPosting = {changed: false, choice: false, stagedCount: 0, editing: false, entered: false};
assert.equal(wizard.shouldConfirmCancel(emptyPosting), false);
for (const change of [{changed: true}, {choice: true}, {stagedCount: 1}, {entered: true}]) {
  assert.equal(wizard.shouldConfirmCancel({...emptyPosting, ...change}), true);
}
assert.equal(wizard.shouldConfirmCancel({...emptyPosting, editing: true, entered: true}), false);
assert.equal(wizard.shouldConfirmCancel({...emptyPosting, editing: true, stagedCount: 1}), true);
console.log(`${checks} type/transaction paths and legacy/Review/comment/cancellation checks passed`);
